config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :calendars
  resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'events#index'

  match '*path' => redirect('/'), via: :all #if Rails.env.production?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calendar.rb
class Calendar < ApplicationRecord
    has_many :events, dependent: :destroy
    belongs_to :user
    validates :title, presence: true
    validates :user_id, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
    validates :title, presence: true
    validates :start, presence: true
    validates :end, presence: true
    validates :user_id, presence: true

    validate :is_end_valid?
    belongs_to :calendar
    belongs_to :event_type
    belongs_to :user

    def start_time
        self.start
    end

    def all_day_event?
      self.start == self.start.midnight && self.end == self.end.midnight ? true : false
    end

    private
      def is_end_valid?
        unless self[:start].nil? or self[:end].nil?
          unless self[:start] <= self[:end]
            errors.add(:end, "cannot be before the start")
          end
        end
      end
end

app/models/event_type.rb
class EventType < ApplicationRecord
    has_many :events, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable :recoverable 
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable
  has_many :events, dependent: :destroy
  has_many :calendars, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  ##################################################################
  private
    def record_not_found
      redirect_to root_path
    end
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_calendar, only: [:show, :edit, :update, :destroy]
  before_action :validate_user, only: [:show, :edit, :update, :destroy]
  before_action :check_authentication, only: [:edit, :update, :destroy]

  # GET /calendars
  # GET /calendars.json
  def index
    redirect_to events_path
    @calendars = current_user.calendars
  end

  # GET /calendars/1
  # GET /calendars/1.json
  def show
  end

  # GET /calendars/new
  def new
    @calendar = current_user.calendars.build
  end

  # GET /calendars/1/edit
  def edit
  end

  # POST /calendars
  # POST /calendars.json
  def create
    @calendar = current_user.calendars.build(calendar_params)

    respond_to do |format|
      if @calendar.save
        format.html { redirect_to @calendar, notice: 'Calendar was successfully created.' }
        format.json { render :show, status: :created, location: @calendar }
      else
        format.html { render :new }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calendars/1
  # PATCH/PUT /calendars/1.json
  def update
    respond_to do |format|
      if @calendar.update(calendar_params)
        format.html { redirect_to @calendar, notice: 'Calendar was successfully updated.' }
        format.json { render :show, status: :ok, location: @calendar }
      else
        format.html { render :edit }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calendars/1
  # DELETE /calendars/1.json
  def destroy
    @calendar.destroy
    respond_to do |format|
      format.html { redirect_to calendars_url, notice: 'Calendar was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calendar
      @calendar = Calendar.find(params[:id])
    end

    def validate_user
      unless current_user.calendars.include?(@calendar)
        format.html { redirect_to events_url, notice: 'You tried to access a page without proper authentication.' }
      end
    end

    def check_authentication
      unless @calendar.user == current_user
        format.html { redirect_to events_url, notice: 'You tried to access a page without proper authentication.' }
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def calendar_params
      params.require(:calendar).permit(:title, :description)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :validate_user, only: [:show, :edit, :update, :destroy]
  before_action :check_authentication, only: [:edit, :update, :destroy]
  # GET /events
  # GET /events.json
  def index
    @events = Event.none
    @calendars=[]
    @calendars = current_user.calendars
    current_user.calendars.each do |calendar|
      @events = @events.or calendar.events
    end
    @categories = EventType.all
    if @categories.nil?
      @categories = []
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    if current_user.calendars.count<1
      format.html { redirect_to new_calendar_path, notice: 'You need at least 1 calendar to create and event.' }
    end
    @event = current_user.events.build
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.events.build(event_params)
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    def validate_user
      unless current_user.calendars.include?(@event.calendar)
        format.html { redirect_to events_url, notice: 'You tried to access a page without proper authentication.' }
      end
    end

    def check_authentication
      unless @event.user == current_user
        format.html { redirect_to events_url, notice: 'You tried to access a page without proper authentication.' }
      end
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :event_type_id, :venue, :start, :end, :description, :calendar_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/events_helper.rb
module EventsHelper
    def nil_helper(field)
        if(field==nil)
            ""
        else
            field.event_type
        end
    end
end

app/views/calendars/_calendar_list.html.erb
<div class="list-group">
  <strong class="list-group-item black">
    Calendars
    <i class="pull-right">
      <%= link_to('<span class="glyphicon glyphicon-plus"></span>'.html_safe,
                    new_calendar_path, title: "Add Calendar", class: "black") %>
    </i>
  </strong>
  <% if @calendars.count < 1 %>
    <div class="list-group-item">
      <em>You currently have no calendars. Click on the add button above to create one!</em>
    </div>
  <% end %>
  <% @calendars.each do |calendar| %>
    <div class="list-group-item">
      <span>
        <%= link_to calendar.title, calendar %>
        <span class="pull-right">
          <%= link_to('<span class="glyphicon glyphicon-pencil"></span>'.html_safe,
                        edit_calendar_path(calendar),
                         title: "Edit Calendar") %>
          <%= link_to('<span class="glyphicon glyphicon-trash"></span>'.html_safe, calendar,
                      method: :delete, data: { confirm: 'This will delete all events associated with this calendar.' },
                       title: "Delete Calendar") %>
        </span>
      </span>
    </div>
  <% end %>
</div>

app/views/calendars/_form.html.erb
<%= form_for(calendar) do |f| %>
  <% if calendar.errors.any? %>
    <div class="list-group" id="error_explanation">
      <div class="list-group-item list-group-item-danger">
        <%= pluralize(calendar.errors.count, "error") %> prohibited this event from being saved:
      </div>
      <ul class="list-group-item">
        <% calendar.errors.full_messages.each do |message| %>
          <li class="list-group-item-text">
            <%= message %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, placeholder: :title, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description , class: "form-control"%>
    </div>

    <div class="actions pull-right">
      <%= link_to 'Back', :back, class: "btn black" %>
      <%= f.submit class: "btn btn-primary"%>
    </div>
<% end %>

app/views/calendars/edit.html.erb
<h1>Editing Calendar</h1>

<%= render 'form', calendar: @calendar %>

app/views/calendars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Calendars</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @calendars.each do |calendar| %>
      <tr>
        <td><%= calendar.title %></td>
        <td><%= calendar.description %></td>
        <td><%= link_to 'Show', calendar %></td>
        <td><%= link_to 'Edit', edit_calendar_path(calendar) %></td>
        <td><%= link_to 'Delete', calendar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Calendar', new_calendar_path %>|
<%= link_to 'Back', root_path %>

app/views/calendars/new.html.erb
<h1>New Calendar</h1>

<%= render 'form', calendar: @calendar %>

app/views/calendars/show.html.erb
<p>
  <h1><%= @calendar.title %></h1>
</p>

<p>
  <strong>Description:</strong>
  <%= @calendar.description %>
</p>

<div class="pull-right">
  <%= link_to 'Back', events_path, class: "btn black" %>
  <%= link_to 'Edit', edit_calendar_path(@calendar), class: "btn btn-primary" %>
</div>

app/views/events/_category_list.html.erb
<div class="list-group">
  <strong class="list-group-item black">Legend</strong>

  <% @categories.each do |category| %>
    <div class="list-group-item <%= category.event_type %>">
      <%= category.event_type %>
    </div>
  <% end %>
</div>

app/views/events/_events_action.html.erb
<div class="list-group">
  <% if current_user.calendars.count>0 %>
    <span class="list-group-item black">
      <strong>Event</strong>
      <span class="pull-right">
        <%= link_to('<span class="glyphicon glyphicon-plus"></span>'.html_safe,
                      new_event_path, title: "Add Event", class: "black") %>
      </span>
    </span>
  <% end %>
</div>

app/views/events/_form.html.erb
<%= form_for(event) do |f| %>
  <% if event.errors.any? %>
    <div class="list-group" id="error_explanation">
      <div class="list-group-item list-group-item-danger">
        <%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:
      </div>
      <ul class="list-group-item">
        <% event.errors.full_messages.each do |message| %>
          <li class="list-group-item-text">
            <%= message %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, placeholder: :title, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :event_type_id %>
      <%= f.collection_select(:event_type_id, EventType.all,
                      :id, :event_type, {:prompt => 'Select event type'}, class: "form-control") %>
    </div>

    <div class="form-group">
      <%= f.label :venue %>
      <%= f.text_field :venue , class: "form-control"%>
    </div>

    <div class="form-inline">
      <div class="form-group col-6">
        <%= f.label :start %>
        <div class='input-group date' id='datetimepicker_start'>
          <%= f.text_field :start, class: 'form-control' %>
          <span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
          </span>
        </div>
      </div>


      <div class="form-group col-6">
        <%= f.label :end %>
        <div class='input-group date' id='datetimepicker_end'>
          <%= f.text_field :end, class: 'form-control' %>
          <span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
          </span>
        </div>
      </div>
    </div>
    <script type="text/javascript">
    $(function () {
            $('#datetimepicker_start').datetimepicker({
              format: 'YYYY-MM-DD HH:mm',
              sideBySide: true
            });
            $('#datetimepicker_end').datetimepicker({
                useCurrent: false, //Important! See issue #1075
                format: 'YYYY-MM-DD HH:mm',
                //inline: true,
                sideBySide: true,
                //collapse: true
            });
            $("#datetimepicker_start").on("dp.change", function (e) {
                $('#datetimepicker_end').data("DateTimePicker").minDate(e.date);
            });

            $("#datetimepicker_end").on("dp.change", function (e) {
                $('#datetimepicker_start').data("DateTimePicker").maxDate(e.date);
            });
        });
    </script>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description , class: "form-control"%>
    </div>

    <div class="form-group">
      <%= f.label :calendar_id %>
      <%= f.collection_select(:calendar_id, current_user.calendars,
                    :id, :title, {:prompt => 'Select calendar'}, class: "form-control") %>
    </div>

    <div class="actions pull-right">
      <%= link_to 'Back', :back, class: "btn black" %>
      <%= f.submit class: "btn btn-primary"%>
    </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

app/views/events/index.html.erb
<%= month_calendar events: @events do |date, events| %>
  <%= date.day %>

  <% events.each do |event| %>
    <div class = "<%= event.event_type.event_type %>">
      <%= link_to event.title, event %>
    </div>
  <% end %>
<% end %>

<% content_for(:upper_side_bar) do %>
  <%= render 'calendars/calendar_list' %>
<% end %>

<% content_for(:event_action) do %>
  <%= render 'events/events_action' %>
<% end %>

<% content_for(:lower_side_bar) do %>
  <%= render 'events/category_list' %>
<% end %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

app/views/events/show.html.erb
<h1><%= @event.title %></h1>

in <%= link_to @event.calendar.title, @event.calendar %>, category <%=link_to @event.event_type.event_type %>

<p>
  <strong>Venue:</strong>
  <%= @event.venue %>
</p>

<p>
  <strong>Start:</strong>
  <%= @event.start.to_formatted_s(:long)  %>
</p>

<p>
  <strong>End:</strong>
  <%= @event.end.to_formatted_s(:long)  %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<div class="pull-right">
  <%= link_to 'Back', events_path, class: "btn black" %>
  <%= link_to 'Edit', edit_event_path(@event), class: "btn btn-primary" %>
  <%= link_to 'Delete', @event, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
</div>

app/views/layouts/_header.html.erb
<div class="wrapper">
    <nav class="navbar">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-nav navbar-brand navbar-left" href="/">CalendarHub</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navigation">
            <ul class="nav navbar-nav navbar-right">
                <!-- <li><a href="#">About</a></li>
                <li><a href="#">Features</a></li> -->
                <% if user_signed_in? %>
                  <li><%= link_to '<span class="glyphicon glyphicon-off"></span> Sign out'.html_safe, destroy_user_session_path, :method => :delete %></li>
                <% else %>
                  <li><%= link_to "Sign up", new_user_registration_path %></li>
                  <li><%= link_to "Login", new_user_session_path, class:'btn black' %></li>
                <% end %>
            </ul>
        </div>
      </div>
    </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CalApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head

  <body>
    <%= render 'layouts/header'%>
    <div class="container">
      <% flash.each do |name, msg| %>
        <% if name == "notice" %>
          <%= content_tag :div, msg, class: "alert alert-success" %>
        <% elsif name == "alert"%>
          <%= content_tag :div, msg, class: "alert alert-danger" %>
        <% end %>
      <% end %>
      <div class="row row-fluid">
        <div class="col-md-12">
          <div class="row">
            <% if user_signed_in? %>
              <div class="col-md-9">
                <%= yield %>
              </div>
            <% else %>
              <div class="col-md-6 col-md-push-3">
                <%= yield %>
              </div>
            <% end %>
            <% if user_signed_in? %>
              <div class="col-md-3">
                <div class="row">
                  <div class="col-md-*">
                    <div id="user-account-content">
                      <div class="list-group">
                        <strong class="list-group-item black">
                          <span class="glyphicon glyphicon-user"></span>
                          <%= current_user.email %>
                        </strong>
                          <div class="list-group-item">
                            <%= link_to('<span class="glyphicon glyphicon-cog"></span> Settings'.html_safe, edit_user_registration_path) %>
                          </div>
                          <div class="list-group-item">
                            <%= link_to('<span class="glyphicon glyphicon-off"></span> Sign out'.html_safe, destroy_user_session_path, method: 'delete') %>
                          </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-*">
                    <div id="upper-right-content">
                      <%= yield(:upper_side_bar) %>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-*">
                    <div id="upper-right-content">
                      <%= yield(:event_action) %>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-*">
                    <div id="lower-right-content">
                      <%= yield(:lower_side_bar) %>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar row-fluid">
  <div class="calendar-heading text-center row-fluid">
    <h2>
      <%= link_to '<span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span>'.html_safe, calendar.url_for_previous_view %>
      <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
      <%= link_to '<span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>'.html_safe, calendar.url_for_next_view %>
    </h2>
  </div>

  <table class="table table-striped row-fluid">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>